import SwiftUI
import AppKit

let appVersion = "1.4"

// MARK: - App Delegate

class AppDelegate: NSObject, NSApplicationDelegate {
    func applicationWillFinishLaunching(_ notification: Notification) {
        NSApp.setActivationPolicy(.regular)
    }

    func applicationDidFinishLaunching(_ notification: Notification) {
        if #available(macOS 14.0, *) {
            NSApp.activate()
        } else {
            NSApp.activate(ignoringOtherApps: true)
        }
    }
}

// MARK: - Help Window

private final class HelpWindowManager: NSObject, NSWindowDelegate {
    static let shared = HelpWindowManager()
    private var window: NSWindow?

    func open() {
        if window?.isVisible != true {
            let controller = NSHostingController(rootView: HelpView())
            let w = NSWindow(contentViewController: controller)
            w.title = "Perfect Passwords Grabber Help"
            w.styleMask = [.titled, .closable, .resizable, .miniaturizable]
            w.setContentSize(NSSize(width: 600, height: 520))
            w.center()
            w.delegate = self
            window = w
        }
        window?.makeKeyAndOrderFront(nil)
        if #available(macOS 14.0, *) {
            NSApp.activate()
        } else {
            NSApp.activate(ignoringOtherApps: true)
        }
    }

    func windowWillClose(_ notification: Notification) {
        window = nil
    }
}

// MARK: - App

#if !TESTING
@main
#endif
struct PerfectPasswordsGrabberApp: App {
    @NSApplicationDelegateAdaptor(AppDelegate.self) var appDelegate

    init() {
        Task { await checkForUpdates(silent: true) }
    }

    var body: some Scene {
        WindowGroup("Perfect Passwords Grabber") {
            ContentView()
        }
        .windowResizability(.contentMinSize)
        .defaultSize(width: 820, height: 620)
        .commands {
            CommandGroup(replacing: .appInfo) {
                Button("About Perfect Passwords Grabber") {
                    let urlString = "https://www.grc.com/passwords.htm"
                    let credits = NSMutableAttributedString(
                        string: "Passwords generated by GRC.com\n",
                        attributes: [.font: NSFont.systemFont(ofSize: NSFont.smallSystemFontSize)]
                    )
                    credits.append(NSAttributedString(string: urlString, attributes: [
                        .link: URL(string: urlString)!,
                        .font: NSFont.systemFont(ofSize: NSFont.smallSystemFontSize),
                        .foregroundColor: NSColor.linkColor,
                    ]))
                    NSApp.orderFrontStandardAboutPanel(options: [
                        .applicationName: "Perfect Passwords Grabber",
                        .applicationVersion: appVersion,
                        .credits: credits,
                        .version: "",
                    ])
                }
            }
            CommandGroup(replacing: .help) {
                Button("Perfect Passwords Grabber Help") {
                    HelpWindowManager.shared.open()
                }
                .keyboardShortcut("?", modifiers: .command)

                Button("Check for Updates…") {
                    Task { await checkForUpdates() }
                }
            }
        }
    }
}
