import SwiftUI
import AppKit

// MARK: - App Delegate

class AppDelegate: NSObject, NSApplicationDelegate {
    func applicationWillFinishLaunching(_ notification: Notification) {
        NSApp.setActivationPolicy(.regular)
    }

    func applicationDidFinishLaunching(_ notification: Notification) {
        NSApp.activate(ignoringOtherApps: true)
    }
}

// MARK: - Help Window

private final class HelpWindowManager {
    static let shared = HelpWindowManager()
    private var window: NSWindow?

    func open() {
        if window == nil || !window!.isVisible {
            let controller = NSHostingController(rootView: HelpView())
            let w = NSWindow(contentViewController: controller)
            w.title = "Perfect Password Grabber Help"
            w.styleMask = [.titled, .closable, .resizable, .miniaturizable]
            w.setContentSize(NSSize(width: 600, height: 520))
            w.center()
            window = w
        }
        window?.makeKeyAndOrderFront(nil)
        NSApp.activate(ignoringOtherApps: true)
    }
}

// MARK: - App

@main
struct PerfectPasswordGrabberApp: App {
    @NSApplicationDelegateAdaptor(AppDelegate.self) var appDelegate

    var body: some Scene {
        WindowGroup("Perfect Password Grabber") {
            ContentView()
        }
        .windowResizability(.contentMinSize)
        .defaultSize(width: 820, height: 620)
        .commands {
            CommandGroup(replacing: .appInfo) {
                Button("About Perfect Password Grabber") {
                    let urlString = "https://www.grc.com/passwords.htm"
                    let credits = NSMutableAttributedString(
                        string: "Passwords generated by GRC.com\n",
                        attributes: [.font: NSFont.systemFont(ofSize: NSFont.smallSystemFontSize)]
                    )
                    credits.append(NSAttributedString(string: urlString, attributes: [
                        .link: URL(string: urlString)!,
                        .font: NSFont.systemFont(ofSize: NSFont.smallSystemFontSize),
                        .foregroundColor: NSColor.linkColor,
                    ]))
                    NSApp.orderFrontStandardAboutPanel(options: [
                        .applicationName: "Perfect Password Grabber",
                        .applicationVersion: "1.0",
                        .credits: credits,
                        .version: "",
                    ])
                }
            }
            CommandGroup(replacing: .help) {
                Button("Perfect Password Grabber Help") {
                    HelpWindowManager.shared.open()
                }
                .keyboardShortcut("?", modifiers: .command)
            }
        }
    }
}
